packages:
  - 'packages/searchlib'
  - 'packages/searchlib-middleware'
  - 'packages/searchlib-less'
  - 'packages/searchlib-globalsearch'
  - 'packages/demo'
  - 'packages/wise'
  - 'apps/searchlib-standalone'
link-workspace-packages: true
prefer-workspace-packages: true
