const vocab = {
  language: {
    ar: 'العربية (ar)',
    bg: 'Български (bg)',
    bs: 'bosanski (bs)',
    cs: 'čeština (cs)',
    da: 'dansk (da)',
    de: 'Deutsch (de)',
    el: 'ελληνικά (el)',
    en: 'English (en)',
    es: 'Español (es)',
    et: 'eesti (et)',
    fi: 'Suomi (fi)',
    fr: 'Français (fr)',
    ga: 'Gaeilge (ga)',
    hr: 'Hrvatski (hr)',
    hu: 'magyar (hu)',
    is: 'Íslenska (is)',
    it: 'italiano (it)',
    lt: 'lietuvių (lt)',
    lv: 'Latviešu (lv)',
    mk: 'македонски (mk)',
    mt: 'Malti (mt)',
    nl: 'Nederlands (nl)',
    no: 'Norsk (no)',
    pl: 'polski (pl)',
    pt: 'Português (pt)',
    ro: 'Română (ro)',
    ru: 'русский (ru)',
    sk: 'slovenčina (sk)',
    sl: 'Slovenščina (sl)',
    sq: 'Shqip (sq)',
    sr: 'Српски (sr)',
    sv: 'Svenska (sv)',
    tr: 'Türkçe (tr)',
  },
};

export default { vocab };
